# Generated by Django 4.2.23 on 2025-07-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_avatar_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='main_portal_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID from the main Alpha Labs portal for SSO', max_length=100, null=True),
        ),
    ]
