# Generated by Django 4.2.23 on 2025-07-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='resolution_quality',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='staff_helpfulness',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='would_recommend',
        ),
        migrations.AddField(
            model_name='feedback',
            name='responses',
            field=models.JSONField(default=dict, help_text='Key-value pairs of questions and user-provided ratings/answers'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='template',
            field=models.ForeignKey(help_text='The feedback template used for this submission', null=True, on_delete=django.db.models.deletion.PROTECT, to='feedback.feedbacktemplate'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, help_text='General-purpose comment field', max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the feedback was submitted'),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the template was created'),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description of when and how this template should be used'),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this template is currently active and available for use'),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='name',
            field=models.CharField(help_text='Name of the feedback template', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='questions',
            field=models.JSONField(default=list, help_text='List of questions for this feedback template in JSON format'),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the template was last updated'),
        ),
    ]
