# Generated by Django 4.2.23 on 2025-07-25 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for these metrics', unique=True)),
                ('total_complaints', models.PositiveIntegerField(default=0)),
                ('new_complaints', models.PositiveIntegerField(default=0)),
                ('resolved_complaints', models.PositiveIntegerField(default=0)),
                ('closed_complaints', models.PositiveIntegerField(default=0)),
                ('avg_resolution_time_hours', models.FloatField(blank=True, help_text='Average time to resolve complaints in hours', null=True)),
                ('department_stats', models.JSONField(default=dict, help_text='Breakdown of complaints by department')),
                ('type_stats', models.JSONField(default=dict, help_text='Breakdown of complaints by type')),
                ('urgency_stats', models.JSONField(default=dict, help_text='Breakdown of complaints by urgency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint Metrics',
                'verbose_name_plural': 'Complaint Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why the status was changed')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='User who made this status change', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(help_text='The complaint this status change belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint')),
                ('new_status', models.ForeignKey(help_text='New status after this change', on_delete=django.db.models.deletion.PROTECT, related_name='new_status_changes', to='complaints.status')),
                ('previous_status', models.ForeignKey(blank=True, help_text='Previous status before this change', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_status_changes', to='complaints.status')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
