# Generated by Django 4.2.23 on 2025-07-27 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0002_complaintmetrics_statushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the remark was created')),
                ('is_internal_note', models.BooleanField(default=False, help_text='True if this note is only visible to internal IT staff')),
            ],
            options={
                'verbose_name': 'Remark',
                'verbose_name_plural': 'Remarks',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ComplaintMetrics',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolution_notes',
        ),
        migrations.AddField(
            model_name='remark',
            name='complaint',
            field=models.ForeignKey(help_text='The complaint this remark belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='remark',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who made the remark', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
