# Generated by Django 4.2.23 on 2025-07-28 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0003_remark_delete_complaintmetrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 (unhappy) to 5 (very happy)')),
                ('feedback_text', models.TextField(blank=True, help_text='Optional feedback text from the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(help_text='The complaint this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='complaint_feedback', to='complaints.complaint')),
                ('user', models.ForeignKey(help_text='User who provided the feedback', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Feedback',
                'verbose_name_plural': 'Complaint Feedback',
            },
        ),
        migrations.CreateModel(
            name='ComplaintClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_closing_remark', models.TextField(help_text='Staff remark when closing the complaint')),
                ('staff_closed_at', models.DateTimeField(auto_now_add=True)),
                ('user_satisfied', models.BooleanField(blank=True, help_text='True if user is satisfied, False if not satisfied, None if no response yet', null=True)),
                ('user_closing_remark', models.TextField(blank=True, help_text="User's remark if not satisfied")),
                ('user_closed_at', models.DateTimeField(blank=True, help_text='When user finally closed the complaint', null=True)),
                ('closed_by_staff', models.ForeignKey(help_text='Staff member who closed the complaint', on_delete=django.db.models.deletion.CASCADE, related_name='staff_closings', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(help_text='The complaint being closed', on_delete=django.db.models.deletion.CASCADE, related_name='closing_details', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Closing',
                'verbose_name_plural': 'Complaint Closings',
            },
        ),
    ]
