# Generated by Django 4.2.23 on 2025-07-28 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0004_complaintfeedback_complaintclosing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintfeedback',
            options={'verbose_name': 'Complaint Feedback', 'verbose_name_plural': 'Complaint Feedbacks'},
        ),
        migrations.RemoveField(
            model_name='complaintfeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='complaintfeedback',
            name='is_satisfied',
            field=models.BooleanField(default=True, help_text='Whether user is satisfied with the resolution'),
        ),
        migrations.AlterField(
            model_name='complaintfeedback',
            name='complaint',
            field=models.OneToOneField(help_text='The complaint this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to='complaints.complaint'),
        ),
        migrations.AlterField(
            model_name='complaintfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the feedback was submitted'),
        ),
        migrations.AlterField(
            model_name='complaintfeedback',
            name='feedback_text',
            field=models.TextField(blank=True, help_text="User's detailed feedback"),
        ),
        migrations.AlterField(
            model_name='complaintfeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='User rating from 1 to 5 stars'),
        ),
        migrations.CreateModel(
            name='ComplaintRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(help_text="User's remark about the resolution")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the remark was added')),
                ('is_read_by_engineer', models.BooleanField(default=False, help_text='Whether the assigned engineer has read this remark')),
                ('complaint', models.ForeignKey(help_text='The complaint this remark is for', on_delete=django.db.models.deletion.CASCADE, related_name='user_remarks', to='complaints.complaint')),
                ('created_by', models.ForeignKey(help_text='User who created the remark', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Remark',
                'verbose_name_plural': 'Complaint Remarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
